displayName=Food De-Colouring
author=Steele
description=Recolors most Hunter and Sailing foods to have less colour like classic foods!
tags=food, consumable, color, recolor, coloring, recoloring, sprite, ui, interface, Hunter, Sailing,
plugins=com.food_decoloring.FoodDeColoringPlugin
build=standard